### ISSUE TITLE
`unmark` shouldn't work for any contact that originally isn't present for the specified date

### ISSUE THREAD

**Issue by superb-sushi** [AY2425S1-CS2103T-F11-2/tp#110]
- now it displays successful unmarking for contacts who do not even have that date in their attendance
![image](https://github.com/user-attachments/assets/5262dab1-ed86-4b8d-a201-e60a88347cad)

**Comment by Rachelcoll** [comment]
Hi, thanks for the review. I think that since the `mark` function applies when a person's attendance is recorded, the `unmark` function should similarly apply to individuals without recorded attendance to maintain consistent behavior. Additionally, if there is no attendance recorded, the functionality of `unmark` remains consistent with its intended purpose.
