### ISSUE TITLE
Bug: `role` field containing special characters cause unexpected behavior with `add` command

### ISSUE THREAD

**Issue by weiliann** [AY2425S1-CS2103T-F11-2/tp#111]
The `role` field in the `add` command is too lenient, allowing special characters like '/' and spaces. Roles like "Member /p999" are accepted but using add r/Member /p999 ... fails because /p is treated as a phone field instead of part of the role.

To reproduce:
`add n/John Doe p/98765432 e/johnd@example.com t/johnDoe12 r/Exco Member p/999 f/`

Suggestion:
Maybe restrict the role field to only accept alphanumeric and special characters like space, dash, underscore, up to your discretion.
`^[a-zA-Z0-9 _-]+$`

**Comment by shizy** [comment]
I think it might be better to not restrict the usage of /, since that could be considered a feature flaw.

We could explicitly state in the user guide instead that " n/", " p/", " t/", " r/" and " f/" are reserved keywords and cannot be used in as part of an existing parameter (even though the non spaced version e.g. "n/" can). This check is already implemented as part of ab3

I think this restriction gives more freedom to the user since we don't have to only allow a seemingly arbitrary subset of special characters, and we can also enforce this behaviour for names, like in issue #113 (we can allow the `/` character)
