### ISSUE TITLE
Bug for feature spec: Allow search by partial role name

### ISSUE THREAD

**Issue by Rachelcoll** [AY2425S1-CS2103T-F11-2/tp#119]
Currently `find` command allows searching by partial name but not allow searching by partial role. For example, `f n/m` can search user with name `Mary` but `f r/ex` can't search for user with role `Exco`, maybe it would be better to make this two searching pattern consistent and allow user to search by partial role name

**Comment by yyihaoc** [comment]
Actually I thought of this before and I was quite hesitant to allow this functionality. Allowing search by partial name is reasonable because users might not be able to remember the full name of a particular person. However, I would presume that there will be a limited set of roles (rather clearly defined) for a CCA and it might make more sense to search the entire role name (or an alias of it). We might run into a problem when searching by partial role name where we are given back unintended results such as having "exco" and "ex-member" and searching by "ex" returns both. Additionally, I allowed any matching substring in searching by partial name such as returning the person named "Amelia" when i search "melia". What does it mean to search "co" and expecting to get a list of people with role "exco" then.

What do you think about this?
