### ISSUE TITLE
Bug: `add` command allows names with more than one space between words

### ISSUE THREAD

**Issue by yyihaoc** [AY2425S1-CS2103T-F11-2/tp#125]
For most if not all names, there is only a single space between words. Having more than one space between words in the name input is likely to be a typo on the user's end. It may make searching using names difficult. 

Perhaps can remove the extra spaces in names.

**Comment by shizy** [comment]
I think removing the extra spaces might be considered overzealous input validation, since users might for some reason want to have multiple consecutive spaces. 

What I think I'll do is to just append a warning that multiple potentially unintended consecutive spaces were detected, and just let the command continue to execute
